### PR TITLE
Remove unintentionally undelivered `phpunit.xml.dist` from `export-ignore`

### LINKED ISSUE #109: Error on a clean skeleton installation after "Which error handler do you want to use during development" step
### Bug Report

 Error on a clean skeleton installation. 

Mezzio-skeleton-error-handler-step

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z
| PHP           | 8.1
| Composer | 2.4.4
| OS             | Win10

#### Summary

Error after "Which error handler do you want to use during development?" question

#### Current behavior

Skeleton not installed. Composer shows an error.

#### How to reproduce

Run composer create-project mezzio/mezzio-skeleton mezzio ( see image) on a win10 device

#### Expected behavior

Skeleton installed.

### PR DESCRIPTION
**Pull request by zonuexe**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

closes https://github.com/mezzio/mezzio-skeleton/issues/109 It was unintentionally missing from the distribution files at https://github.com/mezzio/mezzio-skeleton/pull/97.

I have checked that the following script does not generate any errors.

```sh
git clean -f .
git restore .
rm -r .gitattributes .github .laminas-ci.json phpcs.xml.dist phpunit.xml.dist psalm.xml.dist psalm-baseline.xml renovate.json

yes 1 | composer install
```

Fixes #109

### CODE REVIEW

File: src/MezzioInstaller/OptionalPackages.php [hunk 1]
```diff
@@ -568,21 +568,6 @@ private function cleanUp(): void
...
-    }
-
-    /**
-     * Remove the MezzioInstaller exclusion from the phpunit configuration
-     *
-     * @codeCoverageIgnore
-     */
-    private function preparePhpunitConfig(): void
-    {
-        $phpunitConfigFile = $this->projectRoot . 'phpunit.xml.dist';
```
Comment (Ocramius) [inline src/MezzioInstaller/OptionalPackages.php]: Perhaps just remove `phpunit.xml.dist` from `export-ignore`?

Comment (zonuexe) [reply src/MezzioInstaller/OptionalPackages.php]: ok.

Comment (zonuexe) [reply src/MezzioInstaller/OptionalPackages.php]: @Ocramius I made the appropriate fix and squashed the history.

**Comment by Ocramius** [comment]
I suppose this fixes #109?

**Comment by zonuexe** [comment]
@Ocramius 

Yes, I confirmed the operation by the method written in the PR description.

I've temporarily published the [forked repository](https://packagist.org/packages/zonuexe/mezzio-skeleton-test
) to Packagist, so the command below should also work.

```
composer create-project zonuexe/mezzio-skeleton-test mezzio
```

**Comment by zonuexe** [comment]
It probably makes sense to add a command like the following to CI to test skeleton project.

```
git archive HEAD --worktree-attributes -o archive.tar
(mkdir unarchived && cd unarchived && tar xf ../archive.tar && test -f composer.json && yes 1 | composer install)
```

**Comment by Ocramius** [comment]
@zonuexe ack, CI additions would be nice, so feel free to throw them this way, but meanwhile, I'm merging + releasing this, thank you!
